/* 
 * polymap.org
 * Copyright 2013, Falko Bräutigam. All rights reserved.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */
package org.polymap.rhei.data.entityfeature;

import org.geotools.data.Query;
import org.opengis.feature.Feature;
import org.opengis.feature.type.FeatureType;

import org.polymap.core.model.Entity;

/**
 * In addition to the {@link EntityProvider} this interface allows to manipulate the
 * {@link FeatureType} and {@link Feature} <b>after</b> they were generated by the
 * {@link EntitySourceProcessor} to represent the entities.
 * 
 * @see EntityProvider2
 * @author <a href="http://www.polymap.de">Falko Bräutigam</a>
 */
public interface EntityProvider3<T extends Entity>
        extends EntityProvider<T> {

    public FeatureType buildFeatureType( FeatureType schema );
    
    public Feature buildFeature( Entity entity, Feature feature, FeatureType schema );

    
    /**
     * 
     * @param entity
     * @param propName
     * @param value
     * @return True if the method sucessfully changed the entity; false signals that
     *         the default implementation should by applied after the method
     *         returnes.
     * @throws Exception
     */
    public boolean modifyFeature( Entity entity, String propName, Object value )
    throws Exception;

    public Query transformQuery( Query query );
    
}
